version: '3.7'

services:
  app:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'sirclo'
      MYSQL_USER: 'sirclo'
      MYSQL_PASSWORD: 'sirclo_pass'
      MYSQL_ROOT_PASSWORD: 'r_sirclo_pass'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: {}